### ISSUE TITLE
Confirm is git history needs anything scrubbing before making public

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#1]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Thursday May 14, 2020 at 16:04 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/1_

----

Code comes from a private repo. Code itself can be made public. Desire is to retain history. So only question remains if the developer (git username/email on the commits -or- mentioned within a commit) is good to publish. I'd assume so, but as I thought of it, the question is now asked.

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Sunday May 17, 2020 at 12:03 GMT_

----

One dev not on project contacted Friday via email in the history. Awaiting reply, or publishing with removed.

**Comment by stephen-cox** [comment]
Closed at sprint 1 review.
