### ISSUE TITLE
Simple sitemap

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#11]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Sunday May 17, 2020 at 12:43 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/11_

----

Question:

Require, or optional. Move config / depenency as appropriate.

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Sunday May 17, 2020 at 12:45 GMT_

----

localgov_services_page left config (but removed dependency); suggest moving to optional. Will do with sublanding.

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 11:11 GMT_

----

This just wants some sort of second opinion now I think.

Mainly maybe about using simple sitemap generally. If so to put into core or somewhere?

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 11:12 GMT_

----

I'll assign @finnlewis to be opinionated, just because.

**Comment by ekes** [comment]
<a href="https://github.com/finnlewis"><img src="https://avatars2.githubusercontent.com/u/326588?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [finnlewis](https://github.com/finnlewis)**
_Monday May 18, 2020 at 14:23 GMT_

----

Sounds good. Discussing on call with @andybroomfield and @bhccwebmaster  

let's make simple sitemap a dependency.

**Comment by ekes** [comment]
<a href="https://github.com/finnlewis"><img src="https://avatars2.githubusercontent.com/u/326588?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [finnlewis](https://github.com/finnlewis)**
_Friday May 22, 2020 at 09:56 GMT_

----

So should this live in localgov_core? 
Site-wide dependencies like sitemap, metatags etc... should all live in a central place, right?
Is this localgov_core, localgov_project or localgov https://github.com/localgovdrupal/localgov/blob/master/composer.json ?
@ekes  what do you think?

**Comment by ekes** [comment]
<a href="https://github.com/finnlewis"><img src="https://avatars2.githubusercontent.com/u/326588?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [finnlewis](https://github.com/finnlewis)**
_Friday May 22, 2020 at 14:32 GMT_

----

OK, we now have sitemap module installed as standard. 

As content types are added, we'll need to explore how to deploy preferred default configuration for content types.

I'm guessing the services navigational hierarchy would like to be represented in the sitemap.

**Comment by stephen-cox** [comment]
Closed at sprint 1 review.
