### ISSUE TITLE
Step-by-step summaries aren't rendering correctly on service landing or sub-landing pages 

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_services#110]
Step-by-step summaries aren't being rendered correctly on their parent service landing or sub-landing pages. They are following the pattern:

`Read more about {{ title }} {{ summary }}`

Example from UAT/demo: https://localgovdrupal.agile.coop/births-deaths-marriages-and-citizenship/marriage-and-civil-partnerships

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/261421/118954017-42435600-b955-11eb-99ba-aa7d7a64b00e.png">

**Comment by danchamp** [comment]
Directories are also affected:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/261421/118963133-0c569f80-b95e-11eb-913a-f028a296fa29.png">

**Comment by andybroomfield** [comment]
This will be teasers display mode needs setting up.

**Comment by danchamp** [comment]
@andybroomfield Thanks for the pointer, I will raise issues in Step-by-step and Directories.
