### ISSUE TITLE
Conditional targeting of service status messages

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_services#113]
We've discussed making changes to the way service status messages appear within services

## Currently

Content designers pick a service, and the status message is added to a block on the service landing page

See https://www.brighton-hove.gov.uk/rubbish-recycling-and-streets

<img width="1085" alt="Service message on a landing page" src="https://user-images.githubusercontent.com/708140/119350543-5fe72700-bc97-11eb-9b9d-0230773addb9.png">

We're planning to talk with the Brighton & Hove content team about the effectiveness of this pattern, so it should be left in place for now

## User needs/ evidence

As a content designer
I want to publish a service status message within the content on selected pages of the site
so that I can notify citizens of a change to a specific service

Evidence is limited, but feedback from @benhillsjones and others suggest a service status should be added to all related pages, and immediately beneath the page title and summary. Ben has tried this manually in Croydon with good results

<img width="1161" alt="Status message on service page" src="https://user-images.githubusercontent.com/708140/119349308-ee5aa900-bc95-11eb-91cb-c31275092cf7.png">

## Proposal

Modify the existing service status format

https://localgovdrupal.agile.coop/node/14/edit?destination=/admin/content%3Ftitle%3D%26type%3DAll%26status%3DAll%26langcode%3DAll%26page%3D1

- Impact field sets the status style. Suggest we follow the styles on https://localgovdrupal.agile.coop/service-status for consistency. Click the tabs to see alert-danger, alert-warning and alert-success classes

- Summary is shown in the service message. A "Read more" link takes users to any copy in the body

- Use the same page targeting method as alert banners for consistency

- Apply this to service pages only, initially so it can be shown to a wider group of content designers

**Comment by stephen-cox** [comment]
@willguv @finnlewis I have setup a testing site and deployed the work so far on this for you to take a look at. Basic functionality as described here has been implemented, so any comments on how it works welcome.

Test site is here: https://test.localgov.agile.coop/

The user accounts and passwords are the same as the UAT site.

**Comment by willguv** [comment]
Hi @stephen-cox this looks great!!

I've added a service status message to the following pages initially:

https://test.localgov.agile.coop/adult-health-and-social-care/support-your-home/occupational-therapy-and-equipment-helping-you-stay

https://test.localgov.agile.coop/adult-health-and-social-care/support-your-home/home-monitoring-and-personal-alarms

Thoughts:

- Does this work on all content types or just service page (not a prob, just wondering about testing on other formats)

- I think the summary text should be shown on the specified page, not a truncated version of body text. Then a user clicks "read more" to see everything

- Could the helper text be a bit more helpful?

eg

1) I'm not sure what the effect of a wildcard would be

The '*' character is a wildcard. 

2) <front> is the front page

I don't know how this would be used

**Comment by willguv** [comment]
Hi @stephen-cox had a couple more thoughts on the UX

The "pages" tab is a bit odd - can it be easily removed?

<img width="532" alt="Screenshot 2021-06-02 at 11 54 40" src="https://user-images.githubusercontent.com/708140/120468886-a0caf400-c399-11eb-9341-574da74a8798.png">

Can these two checkboxes appear under the "visibility" title?

Show on landing page
Show on status lists

**Comment by stephen-cox** [comment]
Hi @willguv Thanks for the feedback.

> Does this work on all content types or just service page (not a prob, just wondering about testing on other formats)

It will work anywhere on the site. We would need to think of the UX of just restricting this to services as the pages visibility widget allows you to input any path.

> I think the summary text should be shown on the specified page, not a truncated version of body text.

Yep. This should have been summary text and will update it accordingly.

> Could the helper text be a bit more helpful?

This is part of the field condition widget and it not easily editable (it comes with Drupal core). If this is a major issue there should be a way to change it, but it will involve coding it somehow.

> The "pages" tab is a bit odd - can it be easily removed?

This is also part of the field condition widget as it's possible to have multiple conditions configured (pages, roles, content type or even are custom conditions).

> Can these two checkboxes appear under the "visibility" title?

I'll move them
