### ISSUE TITLE
Service Update

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#13]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 08:35 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/13_

----

Code for this is bundled with `service_hub`/`localgov_services_landing` it wants to be removed.

At the moment it looks like this content type is to be generalized outside services.

TODO
 - [x] Confirm it's to move outside services
Actually it's inside services.

Moved into with all code in services see updates below.

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 08:52 GMT_

----

There's so much services stuff in here that it's worth forking the module again and making a second copy with the services behaviours. Big question about display - it seems it's also wired into the landing page. Generalizing this most simply with just be having a block?

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 11:43 GMT_

----

https://github.com/localgovdrupal/localgov/issues/37#issuecomment-628550805

> >  There is also Service status | service_update_page content type which as yet doesn't exist a a module to move over. I've not checked its dependencies.

> @ekes This is related to services, though is may also be changing its purpose. It originally posts updates about a service under the service landing page in a view. But its also being repurposed into a service status page (eg. Powers this page on Croydon https://new.croydon.gov.uk/service-status) and BHCC has this in UAT.
Historically not widley used in BHCC though recently gaining more use re. Covid. My feeling is that its more of an extras module.

**Comment by ekes** [comment]
<a href="https://github.com/finnlewis"><img src="https://avatars2.githubusercontent.com/u/326588?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [finnlewis](https://github.com/finnlewis)**
_Monday May 18, 2020 at 14:56 GMT_

----

Confirmed that this is dependent on services module. 

- [ ] Factor out to a separate module

- [ ] Locate code that defines current services landing page.

- [ ] Confirm approach / wireframe to 'services updates' page that lists all service updates. Make this optional?

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Tuesday May 19, 2020 at 13:18 GMT_

----

Module itself should be in localgov_services, but can be an optional dependency of the localgov_services top level modules (all the others require each other, this one is an extension).

Most of the code is presently in the services_hub module, so it wants forking a second time to make localgov_services_update with the additional config. 
-OR/AND-
There is _another_ new module, only exists in latest brighton code, that might have all of this much more cleanly pulled together, including the optional views to show a page of services updates etc.

**Comment by ekes** [comment]
<a href="https://github.com/stephen-cox"><img src="https://avatars3.githubusercontent.com/u/7189914?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [stephen-cox](https://github.com/stephen-cox)**
_Thursday May 21, 2020 at 07:21 GMT_

----

Hi @ekes I had a brief look at this yesterday, but it wasn't completely clear to me what needs doing. Perhaps we can discuss later today.

**Comment by ekes** [comment]
<a href="https://github.com/andybroomfield"><img src="https://avatars0.githubusercontent.com/u/1467480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andybroomfield](https://github.com/andybroomfield)**
_Thursday May 21, 2020 at 09:35 GMT_

----

Attached screen shots of where the updates are used for reference.
Also there is a seperate aggregated view of updates from a service, at service name /update.
eg. https://new.brighton-hove.gov.uk/rubbish-recycling-and-streets/update

The combined one page view does not take every service update, but has a dependency on [entityqueue](https://www.drupal.org/project/entityqueue) and service updates must be explicitly added to appear there (and allows the order to be changed).

![Screenshot_2020-05-21 Rubbish, recycling and streets](https://user-images.githubusercontent.com/1467480/82544890-b8985700-9b4d-11ea-98f3-958456fcbc01.png) BHCC Service hub page with service updates turned on (about half way down the page).

![Screenshot_2020-05-21 Latest service updates Brighton Hove City Council(1)](https://user-images.githubusercontent.com/1467480/82551209-b0451980-9b57-11ea-921c-0d11f9bf3e15.png)
 Dedicted service update view for each service (at service/update).

![Screenshot_2020-05-21 Service status Brighton Hove City Council](https://user-images.githubusercontent.com/1467480/82545062-feedb600-9b4d-11ea-89e8-f5feac02096c.png) Combined service updates page

**Comment by ekes** [comment]
<a href="https://github.com/andybroomfield"><img src="https://avatars0.githubusercontent.com/u/1467480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andybroomfield](https://github.com/andybroomfield)**
_Thursday May 21, 2020 at 09:39 GMT_

----

[The Croydon service status page ](https://new.croydon.gov.uk/service-status) is really a page about services status in general, even though they reused the service update content type. This may be more editorial and should be discussed, as the titles used for the service update are the titles of the node, not the service. If /service-status was to be a true aggregate of all the service statuses, then we may need alter how that view is built and move the status field to the service hub itself. Something worth discussing for the future of this feature.

![Screenshot_2020-05-21 Service status London Borough of Croydon](https://user-images.githubusercontent.com/1467480/82545677-ea5ded80-9b4e-11ea-9ecf-1950a56dd842.png)

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Thursday May 21, 2020 at 10:47 GMT_

----

@stephen-cox as a first step I'll pull out the code from the update module that adnan made for brighton, will be easier to review what else might be then needed (config, depenency removal etc)

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Thursday May 21, 2020 at 11:09 GMT_

----

Notes on moving:-
 * Doesn't include the original content type, or content that is shown on the landing page, these need to be exported from croydon.
 * Uses service_status for the content, but service update for the page. Probably can call the page services_status_page ? Down to confusing lines like the entity queue being status but for the page updates.
 * Note: In addition to the services status/update the CSS uses service singular.
 * The enable_service_status field on the localgov_services_landing probably wants to be moved to localgov_service_status to maintain the otherwise independence of the service status module features.

Beyond that reviews can tidy it up to the new use generalised use cases?

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Thursday May 21, 2020 at 12:36 GMT_

----

That code sitting in that branch is everything, it's been massaged a bit to fit together, but it's probably still a real untangle job.

**Comment by ekes** [comment]
<a href="https://github.com/finnlewis"><img src="https://avatars2.githubusercontent.com/u/326588?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [finnlewis](https://github.com/finnlewis)**
_Friday May 22, 2020 at 10:14 GMT_

----

Passing over to @stephen-cox to review.
Considering the naming: service status vs service update. @awalbhc thinks they are different things.

Call it **service status** for now (decided on the call)

**Comment by stephen-cox** [comment]
I've created a separate issue on the best was to resolve the dependency the landing pages have on status pages; #25.

**Comment by stephen-cox** [comment]
User story for service status pages: https://trello.com/c/K7boYO9E/205-as-a-content-designer-create-and-manage-service-status-page
