### ISSUE TITLE
Limit the type of paragraph types available from a service page (duplicate)

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_services#136]
When the subsites module is enabled the full list of paragraph types are available from a service page / overview. 
I think this should be limited to:

- contact
- from library
- link ? 
- topic list builder ? 

However we may need input from the current councils in to this.

**Comment by andybroomfield** [comment]
Is this the page components?
Thats interesting, I didn't know they got installed. We where thinking of going the other way and adding subsites paragraph functionality to the service page structure to make them more curated. (We where going to add this as a custom field though or through core layout builder).

**Comment by msayoung** [comment]
yes, the page components. 

The issue is that by default the page component field on the services pages just allows all types, so when you add the Subsites feature there's loads of options that shouldn't be there (and is quite overwhelming). 

I think by default we should limit it to those 4 above, and then if individual councils want to add more it's an easy config change.

**Comment by andybroomfield** [comment]
@msayoung That makes sense, I'd go ahead with that.

**Comment by keelanfh** [comment]
I would be very much in favour of this! We are using just a few of the paragraph types (most importantly, the contact component). It is quite overwhelming and increases the risk of someone introducing something unintended or not styled correctly.

**Comment by keelanfh** [comment]
This issue duplicates https://github.com/localgovdrupal/localgov_paragraphs/issues/254 - there's some more discussion there

**Comment by willguv** [comment]
Closing in favour of the [duplicate issue](https://github.com/localgovdrupal/localgov_paragraphs/issues/254)
