### ISSUE TITLE
Cannot reference 2nd-level nodes when content access module enabled

### ISSUE THREAD

**Issue by graham-web** [localgovdrupal/localgov_services#147]
To allow configuring permissions per-node, we tried adding the [Content Access](https://www.drupal.org/project/content_access) module to a localgov site.

Unfortunately, when this is enabled, it is no longer possible to save certain content on the site without having 'bypass node access' permission.

### Steps to reproduce:

1. Create content
- service landing page
- service sub-landing page, with first page as parent

2. Enable Content Access (& rebuild node permissions when prompted)
3. Open edit form for sub-landing page
4. Click Save

On affected pages, we see the message `This entity (node: 10551) cannot be referenced.`
(The nid in the error message refers to the node in the Services: Parent field.)

### Analysis
The reason for this is an unfortunate interaction between Localgov's EntityReferenceSelection plugin and the node_access system. The query generated appears to be looking for grant entries not only for the parent entity (10551) but also the parent's parent!

Where the parent node has no parent (i.e. top level landing page), the validation query returns no results.

Failing query: (slightly simplified , to remove unused grant types/realms)
```
SELECT base_table.vid AS vid, base_table.nid AS nid, node_field_data_2.title AS title, node_field_data_3.title AS node_field_data_3_title, node.nid
FROM
    node base_table
INNER JOIN node_field_data node_field_data ON node_field_data.nid = base_table.nid
    LEFT JOIN node__localgov_services_parent node__localgov_services_parent ON node__localgov_services_parent.entity_id = base_table.nid
    LEFT OUTER JOIN node node ON node.nid = node__localgov_services_parent.localgov_services_parent_target_id
    LEFT JOIN node_field_data node_field_data_2 ON node_field_data_2.nid = node.nid
    LEFT JOIN node_field_data node_field_data_3 ON node_field_data_3.nid = base_table.nid
WHERE (node_field_data.type IN ('localgov_services_landing', 'localgov_services_sublanding')) AND (node_field_data.nid IN (10551)) AND (EXISTS (SELECT na.nid AS nid
    FROM
    node_access na
    WHERE ((gid IN (0)) AND (realm = 'all')) AND (na.grant_view >= 1) AND ((base_table.nid = na.nid))))
  AND (EXISTS (SELECT na.nid AS nid
    FROM
    node_access na
    WHERE ((gid IN (0)) AND (realm = 'all')) AND (na.grant_view >= 1) AND ((node.nid = na.nid))))
ORDER BY node_field_data_2.title ASC, node_field_data_3.title ASC
```

This second node_access subquery is created by the sort handler in `ServicesSelection::buildEntityQuery` -

Commenting the line `$query->sort('localgov_services_parent.entity:node.title', 'ASC');` fixes the issue, but available entities are no longer sorted as well in the auto-complete dropdown.

**Comment by graham-web** [comment]
Best idea we currently have is to remove the sort and re-add it using another query alter hook, after node_access has run. Hope to give that a try in the coming days.

**Comment by amoebanath** [comment]
Hmmm upon retesting, this doesn't quite get the same results in the same order :( 

Most importantly, 'Council tax' is not showing up _before_ other Council Tax things with longer names, which it currently does and probably should keep doing.

**Comment by amoebanath** [comment]
Aha - there's a core patch that targets the issue more generally:
[https://www.drupal.org/project/drupal/issues/1349080](https://www.drupal.org/project/drupal/issues/1349080)

So we probably don't need these changes.

**Comment by finnlewis** [comment]
Interesting, if this patch solves the issue, perhaps we should include it in the distribution.

**Comment by finnlewis** [comment]
Hi @amoebanath - did you get any further assessing this? 

Do you think we should include the patch you mentioned or proceed along the lines of your pull request? https://github.com/localgovdrupal/localgov_services/pull/148

**Comment by amoebanath** [comment]
We're using the patch from that core issue, had no issues since.
Looks like it's reached RTBC, so might get adopted soon anyway. But if you know of a number of people bumping into this, then it definitely would be worth including the patch meanwhile.

**Comment by finnlewis** [comment]
Thanks for the update @amoebanath 

@stephen-cox shall we look at testing this and adding it to the distribution?

**Comment by finnlewis** [comment]
@amoebanath @graham-web are you still using the core patch? Should we look at including it ?
