### ISSUE TITLE
WSOD on editing a services landing page if topic is empty

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_services#157]
> Error: Call to a member function label() on null in Drupal\localgov_services_navigation\EntityChildRelationshipUi->childrenField() (line 179 of modules/contrib/localgov_services/modules/localgov_services_navigation/src/EntityChildRelationshipUi.php).

Debugging this line
````php
      $topics = [];
      if ($child->hasField('localgov_topic_classified')) {
        foreach ($child->localgov_topic_classified as $topic) {
          $topics[] = Html::escape($topic->entity->label());
        }
      }
````
So maybe if a topic was deleted there is an error here?

**Comment by andybroomfield** [comment]
I can bypass it by wrapping an `if (!empty($topic->entity))` block, but thats really bypassing an issue.

**Comment by ekes** [comment]
If we could use `?->` that would be nice.

But it's not bypassing an issue. It is correct Drupal (core) behaviour that an entity reference field does not update if the entity itself is deleted. It is the responsibility of the caller to check the entity is still there.

**Comment by andybroomfield** [comment]
Just to confirm it is the deleted taxonomy topic.
Resaving the offending content fixes the issue, but it will crop up again if another topic is deleted.

**Comment by ekes** [comment]
Yes this is correct when you delete an entity core does not go and look at all entity reference fields that could reference it and update them. It is the responsibility of any code using an entity reference field value to check the entity still exists before trying to use it.

So your empty() suggestion is correct; and when are PHP8 only we can use the 'null-safe operator' `?->` but not yet.
