### ISSUE TITLE
The drupal/condition_field patches failed to apply

### ISSUE THREAD

**Issue by tran-bigbluedoor** [localgovdrupal/localgov_services#165]
Currently, the drupal/condition_field patches are blocking update/install with composer:

<img width="1215" alt="Screenshot 2022-06-01 at 15 10 19" src="https://user-images.githubusercontent.com/102959744/171441539-761ea4fb-4984-4847-88dc-e1f1a6c351fc.png">

Suggestion: Remove the patches from composer.json because the new version of drupal/condition_field module has already applied these changes from the patches.

**Comment by stephen-cox** [comment]
@tran-bigbluedoor @louwrense This issue should now be fixed with the [Alert Banner 1.4.1](https://github.com/localgovdrupal/localgov_alert_banner/releases/tag/1.4.1) and [Services 2.0.10](https://github.com/localgovdrupal/localgov_services/releases/tag/2.0.10) releases.
