### ISSUE TITLE
Topics: fields

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#17]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Friday May 22, 2020 at 09:16 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/18_

----

`field_topics` is only used by the paragraphs collecting and linking to content in the `localgov_services_sublanding` content type. This is referring _to_ content and the term, not 'tagging with' or 'putting in' taxonomy term. Content that is tagged with the term uses `field_topic_term`. 

If `field_topics` were named something clearer `sublanding_topics` maybe, it might stop confusing at least me!

**Comment by ekes** [comment]
Adding this to be part of the Topics review. Which starts in Sprint 3

**Comment by ekes** [comment]
With the removal of private fields. The only thing remaining in services would be potentially renaming the sublanding page paragraph field from field_topic_terms and the landing page field_popular_topics localgovdrupal/localgov_topics#4

**Comment by stephen-cox** [comment]
Closing at sprint 3
