### ISSUE TITLE
Search results: set consistent view mode [localgov_services]

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_services#172]
As part of reviewing the search functionality, it has become apparent that there is no consistent presentation of search results across the distribution.

We need to 

- [ ] ensure each content type has a search_result display node
- [ ] configure the search_result display mode to have the appropriate fields

In the case of localgov_services, we need to ensure appropriate configuration for 

- [ ] localgov_services_landing
- [ ] localgov_services_sublanding
- [ ] localgov_services_page

**Comment by ekes** [comment]
https://github.com/wfcouncil/localgov_solr_search/ had done some configuration for specific services search results.

**Comment by andybroomfield** [comment]
For now, I think we just add the highlight results and then if Product group want to change the default we can change this.
