### ISSUE TITLE
Form display

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#18]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Friday May 22, 2020 at 09:50 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/19_

----

Current situation:

 - [x] landing page - groups disabled - basic fields only visible
 - [x] sublanding page - some groups errors
 - [x] page - as sublanding

Further work is probably writing a new issue for theme.

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Friday May 22, 2020 at 12:33 GMT_

----

Using admin theme for content creation would pretty much fix the other layout issues for now.

**Comment by ekes** [comment]
<a href="https://github.com/andybroomfield"><img src="https://avatars0.githubusercontent.com/u/1467480?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andybroomfield](https://github.com/andybroomfield)**
_Friday May 22, 2020 at 13:13 GMT_

----

General position at BHCC is that the admin theme is used for content creation.
There may be some for fixes in the BHCC theme as thats also used for webforms.

**Comment by ekes** [comment]
Pull request localgovdrupal/localgov#52 for defaulting the admin theme. Is the last thing on this one.

**Comment by stephen-cox** [comment]
Closed at sprint 1 review.
