### ISSUE TITLE
Can't reference an internal page that is a view (and possible other non node pages)

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_services#185]
See original issue on our repo below:
However since our `LinkNodeReferenceViewMode` largley duplicates `LinkNodeReference` I belive the problem is there.
We solved it by also throwing an exception if the route paremters (which it tries to key an entity type from) are empty.
````php
if (empty($entity_type)) {
  throw new \UnexpectedValueException('Entity type is empty');
}
````
However looking at the code there, it could do with some tiding up on determing if the entity is valid before trying to load it etc.

Original issue below for reference:

> When trying to add the link to the parking zones map relativley
> /parking-zones
> as this is a view, it causes a crash on the page as it looks like its trying to render as a node teaser / card.
> 
> Stacktrace looks like it is in bhcc_services.
> > Drupal\Component\Plugin\Exception\PluginNotFoundException: The "" entity type does not exist. in Drupal\Core\Entity\EntityTypeManager->getDefinition() (line 139 of core/lib/Drupal/Core/Entity/EntityTypeManager.php).
> Drupal\Core\Entity\EntityTypeManager->getHandler(NULL, 'storage') (Line: 192)
> Drupal\Core\Entity\EntityTypeManager->getStorage(NULL) (Line: 136)
> Drupal\bhcc_services\Plugin\Field\FieldFormatter\LinkNodeReferenceViewMode->buildInternal(Object, 'en') (Line: 95)
> Drupal\bhcc_services\Plugin\Field\FieldFormatter\LinkNodeReferenceViewMode->viewElements(Object, 'en') (Line: 89)
> 
> May also be in the localgov_services field formatter which this is based on.

**Comment by finnlewis** [comment]
This is fixed with https://github.com/localgovdrupal/localgov_services/pull/191 and the latest release.
