### ISSUE TITLE
Service status with empty body causes crash.

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_services#200]
To reproduce:
1) Create a service status node with no body text. Assign it to a service landing page. Publish and save it.
2) View the service landing page the service status was assigned to. You'll get an error, instead of the service landing page.

Logged error is:
`
Error: Call to a member function getValue() on null in Drupal\localgov_services_status\ServiceStatus->getStatusUpdates() (line 116 of /var/www/html/web/modules/contrib/localgov_services/modules/localgov_services_status/src/ServiceStatus.php)
#0 /var/www/html/web/modules/contrib/localgov_services/modules/localgov_services_status/src/ServiceStatus.php(59): Drupal\localgov_services_status\ServiceStatus->getStatusUpdates(Object(Drupal\node\Entity\Node), 2, false, true)
#1 /var/www/html/web/modules/contrib/localgov_services/modules/localgov_services_status/localgov_services_status.module(116): Drupal\localgov_services_status\ServiceStatus->getStatusForBlock(Object(Drupal\node\Entity\Node))
`

**Comment by stephen-cox** [comment]
The body field on a service status page is required out of the box as the summary is used in block and listings. A quick fix is to add a summary to the status, but we should be checking if a summary field exists. The offending code is: https://github.com/localgovdrupal/localgov_services/blob/64b56dd2215d38c0aa156a205ae9d3498c982762/modules/localgov_services_status/src/ServiceStatus.php#L116

**Comment by stephen-cox** [comment]
@rupertj This should be fixed in the latest release of Services: https://github.com/localgovdrupal/localgov_services/releases/tag/2.0.17

**Comment by rupertj** [comment]
@stephen-cox Excellent - thanks!
