### ISSUE TITLE
Rationalise task button naming

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_services#203]
The "common tasks" tab is named differently across the CMS

- On service landing pages, it's called "common tasks"
- On service pages, "task buttons"

(I'll check for other instances)

We need to agree the best name for this tab, and update each affected format

**Comment by willguv** [comment]
@benhillsjones one for you and the content group - can you agree on what this tab should be called? Thanks

**Comment by willguv** [comment]
Suggestions from content group - 25 April

- top tasks
- task CTAs
- quick links

Agreed "top tasks"

**Comment by willguv** [comment]
@stephen-cox discussed with the content group. Can you make the following changes please?

On service landing pages, the "common tasks" tab and the heading at the top of the fields should be "Top tasks"

On service pages, the "task buttons" tab and the heading at the top of the fields should be "Top tasks"

By heading I mean the text on the blue background next to "show row weights". Does this have a name?



![Image](https://user-images.githubusercontent.com/708140/234361966-35fee4b9-128d-4b89-afa9-f0caf3ab1bec.png)

**Comment by willguv** [comment]
@stephen-cox it would be good to get this done before product update 3 too as it's been hanging around for a while

Am I right in saying this will just be for new users and we'll need to give existing ones instructions? Thanks

**Comment by stephen-cox** [comment]
> By heading I mean the text on the blue background next to "show row weights". Does this have a name?

This is the field name.

> Am I right in saying this will just be for new users and we'll need to give existing ones instructions?

Yep. There will be two places this needs to be changed for each content type.

It will need to be changed on the field setting page for the `localgov_common_tasks` field (/admin/structure/types/manage/localgov_services_page/fields/node.localgov_services_page.localgov_common_tasks and /admin/structure/types/manage/localgov_services_landing/fields/node.localgov_services_landing.localgov_common_tasks). Where the label needs updating:

![image](https://github.com/localgovdrupal/localgov_services/assets/7189914/95fc23cb-a87b-454f-b776-587edfeebf5f)

Also the tab name will need changing on the form display settings (/admin/structure/types/manage/localgov_services_page/form-display and /admin/structure/types/manage/localgov_services_landing/form-display)

![image](https://github.com/localgovdrupal/localgov_services/assets/7189914/6760e0d1-94de-4bb4-b545-f752b6dd10f6)

**Comment by stephen-cox** [comment]
@willguv The PR #215 adds these changes for new installs.

The node edit forms now look like

![image](https://github.com/localgovdrupal/localgov_services/assets/7189914/d41653c6-d847-4914-9adb-1407ec30fce2)

![image](https://github.com/localgovdrupal/localgov_services/assets/7189914/05a766e6-96a7-46fe-815c-88633ca6418f)

**Comment by willguv** [comment]
@stephen-cox much better, thank you!
