### ISSUE TITLE
Deprecated code: Relying on entity queries to check access by default is deprecated in drupal:9.2.0

### ISSUE THREAD

**Issue by 2dareis2do** [localgovdrupal/localgov_services#206]
When running tests and phpstan

Checking for deprecated code
 337/337 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------------------ 
  Line   modules/contrib/localgov_services/modules/localgov_services_status/src/ServiceStatus.php  
 ------ ------------------------------------------------------------------------------------------ 
  138    Relying on entity queries to check access by                                              
         default is deprecated in drupal:9.2.0 and an error                                        
         will be thrown from drupal:10.0.0. Call                                                   
         \Drupal\Core\Entity\Query\QueryInterface::accessCheck()                                   
         with TRUE or FALSE to specify whether access                                              
         should be checked.                                                                        
         💡 See https://www.drupal.org/node/3201242                                                
 ------ ------------------------------------------------------------------------------------------ 

                                                             
 [ERROR] Found 1 error

**Comment by keelanfh** [comment]
Closed by #212
