### ISSUE TITLE
PHP error when adding alternative paragraph types to sub landing localgov_topics field

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_services#218]
When adding additional paragraph types to the Service sub landing localgov_topics field, adding any content in a non topic list builder, saving the page and then editing it again will result in a PHP error:

> Warning: foreach() argument must be of type array|object, null given in Drupal\localgov_services_navigation\EntityChildRelationshipUi::referencedChildren() (line 230 of modules/contrib/localgov_services/modules/localgov_services_navigation/src/EntityChildRelationshipUi.php).

This is being generated by the services navigation widget that generates link suggestions for the links.

This can be mitigated by reusing the field topic_list_links for the link field, though if you want to have a different (non link) paragraph there the problem will occur.

I think the intention here was to rely on the hard coded field as generally not considered something that would be changed. It is however exposed in Drupal UI so for now a saftey check to handle the PHP error case, and then consider how we might want the existing links widget to work in future.

Steps to replicate:
1. under structure -> content types -> services sub landing, go to manage fields and edit localgov_topics.
2. Under paragraph types, add a second allowed paragraph (eg. text)
3. Edit a service sub landing page and add a paragraph of the second allowed type
4. Save the sublanding page and then click edit again

Expected result:
Edit page opens without PHP error.

Actual result:
PHP error (if messages on, or in the logs) as detailed above.

**Comment by finnlewis** [comment]
Hey @willguv !

We're discussing service sub-landing pages in the Tech Drop-in. 

@andybroomfield is extending / altering the service sub-landing page with some new paragraph types. This caused PHP warnings which we are working around. 

This now pushes the question of "Do we want to reassess the Service Sub-Landing page structure / IA?"

maybe we could discuss this at some point int he Backlog group.
