### ISSUE TITLE
Handling field_enable_service_updates field on localgov_services_landing content type

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_services#25]
This field lives on the landing page and refers to a status page, but we want to make status pages optional. This means we don't want a dependency in localgov_services_landing on localgov_services_status.

The field config for this field can live in localgov_services_status, meaning it's dependant on localgov_services_landing, but we need to handle the form and display settings for this field on a landing page. One option is to have these set on installation of the localgov_services_status module. This is done here: https://github.com/localgovdrupal/localgov_services/blob/feature/13-service-status/modules/localgov_services_status/localgov_services_status.install#L11. It looks a bit fragile to me.

Are there better ways of doing this? One option would be to remove this field and add a reference to the landing page on the status page, but this will cause UX and DX issues.

**Comment by ekes** [comment]
One question: Do services need to opt into service status?

Other options might become apparent from the discussion about how the status / updates want to be used and controlled by the admins: a landing page giving 'good service' or latest update information (or even historical information?); a similar block on the service landing page; optionally or always on all the sub pages? Could these want to be controlled from a central admin page, or within the service only? If so the configuration for which services are listed could be on an separate admin page (and seperate config)?

**Comment by andybroomfield** [comment]
From the current use case at BHCC, services have to opt in to recive updates, as that controls the view that displays on the service landing page. However the status updates at /service-status can be set arbitrarily, as they use entity queue. To make things simpler the checkbox could be done away with and just detect if any where added to the service.

**Comment by stephen-cox** [comment]
We could do away with with field entirely by using a combination of status pages referencing a landing page and being published. We simply won't show unpublished statuses or those that don't reference a landing page. This will make it a little harder for content editors to turn on and off status messages, so perhaps neds some discussion.

**Comment by andybroomfield** [comment]
One thing to be wary of is that regardless of whether service updates are enabled, they can still be posted to the service-status page. This looks like it will be the way its going to get used at BHCC for the time being, allowing service status for all services to be posted, whilst keeping the view restricted to specific services. If we need to remove the field from services it may be worth having an opt in / out for each update on the service status node. (Or the feature split into two).

**Comment by stephen-cox** [comment]
From our meeting this morning we will remove this field and add options for displaying status messages on landing pages and listing views to the status content type.
