### ISSUE TITLE
Services Navigation: opt-ing into become part of Services hierarchy, the 'Service:' field

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#27]
Presently two (or actually three) fields:
 `field_service`
 `field_sub_hub`
and additionally
 `field_service_hub`

content type | `field_service` | `field_sub_hub` | `field_service_hub`
-|--------------------|---------------------- |--------------------------
service sub landing | x | |
service page | x | x |
service status | x | |
document landing | x | x |
step-by-step homepage | x | o |
guide page | x | x | 
directory entry | | | x

Original issue about ***service page*** and ***service sub landing***: #6 
Service status is a quite different beast #13 

Issue about the ***guide page***, possibly one of the more complicated: localgovdrupal/localgov_guides#1

***Document landing pages*** aren't in use on Croydon at the moment - Brighton?

***Step-by-Step homepage*** the `field_sub_hub` is never completed, in all but one case they are surfaced as 'task buttons' on the service landing page, in one case somehow it ends up on a sub landing page even though that's not completed in the field on the step-by-step node.

***Directory entry*** everything in (only) one directory channel is in a Service. The directory channel, nor the entries, seem to be referenced in the Service. The directory entries are manually repeated on a page which is attached to a sub landing page of the service.

Service sublanding, Document landing, step-by-step homepage are all pages with child pages.
Service page, Guide Page and Directory Entry are child pages.

**Comment by ekes** [comment]
The proposal from https://github.com/localgovdrupal/localgov_services/issues/6#issuecomment-634006572 was to replace the two (three) fields with one field with a custom widget.

This would still seem to be a sensible option, if it stores anything other than the direct parent (ie also storing the landing page if it's a sub-landing page) is by this point an implementation detail.

Pending discussion, particularly at the moment about it's use in Guide pages, it seems that the 'landing' or 'homepage' or 'directory channel' should be the item that is placed into a service landing page (or at a stretch sublanding page). The pages getting their 'service' by virtue of being in a 'landing' page or similar that is in a service. 
The parent-child relationships within these component sections then uses separate fields as per their specific use case and can stand alone without the 'landing' page being in a service.

_Any_ content type that has this new 'service field' can then in the future trigger their automatic or suggested inclusion on the appropriate parent service (sub-)landing page. [aside: Current thinking for Service Landing Pages it looks most helpful possibly to make a list of pages that reference the landing page, but are not yet referenced by the landing page by _neither_ the common tasks _nor_ the child pages. Automatically populating them looks less helpful as it could be in either location.]

**Comment by finnlewis** [comment]
I think it makes perfect sense to have a single field to 'opt in' to a service.

Just to be clear, the main meaning of this is that the page (or collection of pages) then *lives* under that service insofar as URL path alias, breadcrumb are set. 

There is currently no automatic assumption that the page that is referencing the service landing page or sub-landing page needs to be linked to from the landing page or sub landing page, as these landing page child links are manually curated. 

We are hoping that we can create a nice 'auto suggestion' widget that will suggest any page that references this landing page as a likely candidate for child page selection.

Either that, or we change it to explicitly require that all pages that reference a landing page are listed as children of that landing page. That to me feels more robust. If there are 'too many pages that reference this landing page' then surely that reveals a more fundamental information architecture problem. Forcing all child pages to be listed might actually help a more balanced information achitecture.

**Comment by ekes** [comment]
> Either that, or we change it to explicitly require that all pages that reference a landing page are listed as children of that landing page. 

Nice but the catch there, which for 'landing pages' at least (not sublanding pages) is that they link to content in both their child entity references, as well as their task links.

**Comment by ekes** [comment]
But to be clear I'm not proposing the implement the suggestion, or auto adding in this sprint, I'm going for facilitating doing so, while cleaning up the IA, and DX of these fields.

**Comment by andybroomfield** [comment]
Will pick this up Monday.
General rules are.
Most content must fit into the services IA, either attached to a service landing page or a hub.
Expcetions are for Campaigns, which are stand alone
Directories, which have a soft link to services (They sit on their own IA, but have a forward link in the directory entry to go onward to a service or sub landing page).
Events (New thing at BHCC) are soft linked to directories, though have their own IA.

**Comment by andybroomfield** [comment]
> _**Document landing pages**_ aren't in use on Croydon at the moment - Brighton?

I assume these are what are called Form start at BHCC?
They are in use, as they are the starting point to go to our form system. Essentially these are just link fields and I belive Croydon replaced these with a paragraph type so they can embed them in service pages. Aside from that the difference is the field widget BHCC uses has the option to redirect through the internal citizenID service.

**Comment by andybroomfield** [comment]
> _**Directory entry**_ everything in (only) one directory channel is in a Service. The directory channel, nor the entries, seem to be referenced in the Service. The directory entries are manually repeated on a page which is attached to a sub landing page of the service.

How directories link through to services and how they fit in the IA I suggest as a discussion for when we work on directories rather than link it to services as theres quite a lot to unbundle particully as directory channels can be arbitary and may be heavily linked to a particular service whereas some will not relate to services at all.

**Comment by andybroomfield** [comment]
Generally, Comms prefer to be able to link to any page from the service landing and sub landing pages, though the IA should still follow the strict pattern of Service landing page -> Sub landing page -> Service page (or parent page for guides etc..) -> Child pages if used. 

Hope above makes sense.

**Comment by ekes** [comment]
andyb:
>  IA should still follow the strict pattern of Service landing page -> Sub landing page -> Service page (or parent page for guides etc..) -> Child pages if used.

ekes:
> it seems that the 'landing' or 'homepage' or 'directory channel' should be the item that is placed into a service landing page (or at a stretch sublanding page). The pages getting their 'service' by virtue of being in a 'landing' page or similar that is in a service.

clarification:

***Services Sublanding pages***, _must_ have a parent Service Landing page.
***Service Pages***, _must_ have a parent Service Sublanding page. The Service landing page of the Sublanding page added to the hierarchy.

***Document landing, Step-by-Step homepage, Guide homepage, Directory Channel***, _can_ have a parent Service Landing page _or_ a parent Service Sublanding page.
***Document page, step-by-step page, guide page, directory entry***, _must_ have a parent Document landing, Step-by-Step homepage, Guide homepage, Directory Channel. _If_ their parent has a parent Service Landing page/Subservice Landing page this is then added to the hierarchy.

So it's the landing page you put into a service - if desired.

**Comment by andybroomfield** [comment]
@ekes I'm going to try and get some clarification on this from our comms team.

Directory Entry (not channel) is only a soft link, as directories exist in their own hireacy, its really a forwarding link. I suspect it may have been simmilar with the other content types in the past.

**Comment by ekes** [comment]
> Directory Entry (not channel) is only a soft link, as directories exist in their own hireacy, its really a forwarding link.

Immediate thought [just logging]: two different fields:- services_parent (enforces hierarchy, generates breadcrumbs paths etc.) services_related (adds a link somewhere to related service, maybe surfaces the related page as something to also be linked to by the relevant service (sub)landing page).

**Comment by andybroomfield** [comment]
Awating feedback from comms team.
I can confirm that on the BHCC site, there is no field_service entity reference on our Guide pages and step by step page. Only on the guide overview and step by step home page, and this is to fit the path aliases so they site as part of the services IA. In that case they become like the service standard page.

At BHCC we tend to have lots of different content types (form start, document page) that hang off the services IA, whereas I belive Croydon are replacing this with paragraph items that sit within the standard page. We're not sure if BHCC would start adopting the Croydon method, though it would defintaly be useful to be able to define content types that can opt in to the IA.

In terms of optional related service, that is what is in use with the directory entry. Here there are directory items which can either be council or third party, so they sit withing their own IA at /directories/[channel]/[listing]. However there is a requirement that they can forward link to a service. Eg on the SEND directory entries, some of them can link forward to the SEND service.

<img width="1353" alt="Screenshot 2020-06-02 at 10 42 06 am" src="https://user-images.githubusercontent.com/1467480/83506933-b922dd00-a4bf-11ea-8a3d-c4957845255c.png">
https://new.brighton-hove.gov.uk/directories/special-educational-needs-and-disability-support/amaze

I've asked the comms team at BHCC if they would want a related services link on guide and step by step pages. It may be something that is more added internally and the distribution keeps the hireachy as intended for simplicity.

**Comment by ekes** [comment]
Committed and documented: https://github.com/localgovdrupal/localgov/wiki/Renamed-fields
