### ISSUE TITLE
Service status updates only appear on a landing pages update page after a cache rebuild

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_services#28]
When the localgov_service_status page is enabled, each service landing page gets an updates page at `/[landing-page-alias]/update`. Statuses only appear here after a cache clear.

These pages are created by an dynamic route specified in `localgov_services_status\Routing\ServiceUpdateRoutes` It would seem some sort of cache invalidation needs adding to this.

**Comment by ekes** [comment]
Reading the code I thought that this was supposed to do this: https://github.com/localgovdrupal/localgov_services/pull/29/files#diff-148a90ac3ac25b78d558fd2f68e42c3fR41

**Comment by ekes** [comment]
Ah! This is the _route_ (to the status page view, which has a {parent_path_alias}/status path) that isn't being cleared?

**Comment by stephen-cox** [comment]
Yep - the route doesn't work until the cache is cleared. I've also had strange results in the tests with changes not displaying which seem to display fine when I check manaully

**Comment by ekes** [comment]
So, still slightly running with this so I'm probably missing things again, but wouldn't it be better to just work with the route to a view with node/%node/status and then add paths either:-

 * Maintain path aliases from parent_alias/status to node/parent_nid/status (hook on creation/deletion of status entities, and updating of the path of the landing node itself, to see if they need adding removing)
 * Or use an inbound / outbound alias and rewrite it -- this is what sub-pathauto does for _all_ subpaths that match an existing alias https://git.drupalcode.org/project/subpathauto/-/blob/8.x-1.x/src/PathProcessor.php#L86 which following @andybroomfield low maintenance option it would be -- but it's pretty all encompassing cycling over everything, great if it's common and everyone wants it, less so if it's not or it gets in the way for some other use case.

**Comment by stephen-cox** [comment]
I don't think I fully understand the implications of the second option. But the first one seems easy enough to implement. 

One complexity being that the current code only defines a route for landing pages with associated status pages that are enabled be shown on listing pages: https://github.com/localgovdrupal/localgov_services/blob/feature/13-service-status/modules/localgov_services_status/src/Routing/ServiceStatusRoutes.php#L27

**Comment by ekes** [comment]
> One complexity being that the current code only defines a route for landing pages with associated status pages that are enabled be shown on listing pages: https://github.com/localgovdrupal/localgov_services/blob/feature/13-service-status/modules/localgov_services_status/src/Routing/ServiceStatusRoutes.php#L27

An access controller that checks should be enough? Although, I seem to recall we opt-ed for if there were status entities posted it existed, and if they weren't posted it didn't? Either way a check needs to be made based on the argument.

**Comment by ekes** [comment]
I won't make a PR for branch `13-service-status--28-routing` into branch `13-service-status` unless folks think it necessary. But a sanity check on: 

https://github.com/localgovdrupal/localgov_services/tree/feature/13-service-status--28-routing

before I merge it would be nice.

**Comment by ekes** [comment]
Merged into the main PR
