### ISSUE TITLE
Review dependencies of localgov_services_sublanding

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#4]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Thursday May 14, 2020 at 16:08 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/4_

----

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Friday May 15, 2020 at 14:36 GMT_

----

@stephen-cox :

Starting to find code dependencies that need sorting. I'm going to move the link_node_reference field formatter from the old bhcc_sub_hub to the localgov_paragraphs module. It only appears to be used on topic_list_builder paragraphs.

Means you'll need to delete this file: https://github.com/localgovdrupal/localgov_services/blob/develop/modules/localgov_services_sublanding/src/Plugin/Field/FieldFormatter/LinkNodeReference.php

**Comment by ekes** [comment]
<a href="https://github.com/stephen-cox"><img src="https://avatars3.githubusercontent.com/u/7189914?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [stephen-cox](https://github.com/stephen-cox)**
_Friday May 15, 2020 at 16:12 GMT_

----

I'm also moving the contents of the .module file and the twig template as these deal with the display of the topic_list_builder paragraph type.

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Sunday May 17, 2020 at 13:36 GMT_

----

I was just doing this. Then stopped for a second.

@stephen-cox  Isn't this paragraph stuff exclusively used for navigating the services (sublanding) pages? Would moving it to a separate paragraphs module (a) add a dependency there on the services content types (b) add specific paragraphs that aren't reused elsewhere?

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 10:51 GMT_

----

Assigned to @stephen-cox for feedback/discussion.

**Comment by ekes** [comment]
<a href="https://github.com/stephen-cox"><img src="https://avatars3.githubusercontent.com/u/7189914?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [stephen-cox](https://github.com/stephen-cox)**
_Thursday May 21, 2020 at 09:51 GMT_

----

Discussion going on here: https://github.com/localgovdrupal/localgov_services/pull/17

**Comment by ekes** [comment]
<a href="https://github.com/stephen-cox"><img src="https://avatars3.githubusercontent.com/u/7189914?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [stephen-cox](https://github.com/stephen-cox)**
_Thursday May 21, 2020 at 11:11 GMT_

----

Passing back to @ekes to determine is anything further is required here.

**Comment by stephen-cox** [comment]
Closed at sprint 1 review.
