### ISSUE TITLE
Latest Status on Landing Page

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#43]
Follow-up to #13 #29 

Block shown on Landing Page that also links to {landing-page}/status.

**Comment by ekes** [comment]
Questions:
 * Can it use a view (with argument) - could the {landing-page}/status itself. There's the example of the sitewide status-update which could just be used?
 * Can it be placed as a block, or does it need to be added to templating? How much flexibility is needed on layout of Landing Page -- TODO Related Issues?
 * If it's added to templating could this be in the localgov_services_status module to keep dependencies clear (status optional, landing required).

**Comment by stephen-cox** [comment]
While reviewing this as part of #40 I have kept the current way of doing things, that is using the `localgov_services_status.service_status` status to load the latest 2 status updates and display these in the page using a template supplied by the localgov_services_status module.

You can see my proposed changes here: https://github.com/localgovdrupal/localgov_services/blob/feature/40-service-templates-and-preprocess-hooks/modules/localgov_services_landing/localgov_services_landing.module#L36

There maybe better ways to do this, but they will involve quite a bit of reworking and this seems the most efficient solution for the time being.

**Comment by ekes** [comment]
Is there a reason to leave it in the services_landing module though, rather than move it to the services_status module? No need to test if it exists then too.

**Comment by stephen-cox** [comment]
Yep - see what you mean. Moved the status page module: https://github.com/localgovdrupal/localgov_services/blob/feature/40-service-templates-and-preprocess-hooks/modules/localgov_services_status/localgov_services_status.module#L51
