### ISSUE TITLE
Services Inward navigation

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#44]
Outward or Upward navigation, and the concept of pages and sublanding pages being in a service committed in #27 

Inward or Downward navigation 'works'. This general issue for notes on to do, or to improve:

 * Topics on sublanding page - in review Sprint 3
 * Suggestions of pages linking to the Landing or Sublanding page (that aren't yet linked to by that page)

**Comment by finnlewis** [comment]
@ekes 
You were going to check on this one to confirm if it is 'done' or if there's anything else left to do.

**Comment by ekes** [comment]
Got merged in #56 so done.
The follow-up #59 got done too.
