### ISSUE TITLE
Service status is in the wrong order

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_services#45]
With the merge of #29 service status is now at /service-status.

These are showing the pages in the wrong order. 
They are: limited -> revised -> normal.
They should be revised (major disruption) -> limited (some delays) -> normal.

![Screenshot_2020-06-09 Service status Drush Site-Install](https://user-images.githubusercontent.com/1467480/84180441-67f68880-aa7f-11ea-9ab4-aaa8db61662f.png)

**Comment by ekes** [comment]
The naming to keys hasn't changed:

```
0-severe-impact|Limited service
1-has-issues|Revised service
2-no-issues|Normal service
```

So Limited service is Severe Impact "There are severe issues impacting the running of this service"
And Revised service is Has Issues "This service has a number of issues that affect the way it runs"

**Comment by andybroomfield** [comment]
@ekes Ahh, ok. I think I'm going by what is on a [Trello ticket](https://trello.com/c/K7boYO9E/205-as-a-content-designer-create-and-manage-service-statuses) which has it in that order. That might be something we review when we talk to comms / content designers on the labels people might use.

**Comment by finnlewis** [comment]
This needs reviewing with product group.

**Comment by willguv** [comment]
Please use the machine names as defaults - thanks @ekes 

If it's easy for councils to customise, this is all fine

**Comment by ekes** [comment]
So they're brutal, but honest as listed above:-

'Severe impact'; 'Has issues', 'No issues'.
