### ISSUE TITLE
Child field pages can't reference step-by-step

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#59]
> I have found a bug. It is possible to drag guide and step by step pages into the child pages fields, but these are not acceptable content types for this field so you end up with an error

**Comment by ekes** [comment]
Should be able to reference any content type that has the `localgov_services_parent` entity reference field pointing to it.

**Comment by finnlewis** [comment]
@ekes @stephen-cox how do you think this should work? 

Option 1. 
On install of guide pages, it checks for the existence of the services mogules / content types / fields and alters the configuration for the child page entity reference to allow guide pages. 

Option 2.
The 'unattended children lister' checks which content types can be referenced by the child page entity reference field and limits the list to those content types.

Maybe there are other options?

**Comment by ekes** [comment]
I was just thinking: Work out where to hook in to catch the `localgov_services_parent` field being  added to a content type, then add it to the list of accepted content types (and the inverse when removed).
