### ISSUE TITLE
Services Navigation

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#6]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Sunday May 17, 2020 at 09:13 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/6_

----

 ## Current situation

 ### Within the Services section

 * Page entity : reference sublanding and landing - with additional field for direct parent
 * Sublanding : reference landing - paragraphs field with topic builder and manual links list to pages and elsewhere
 * Landing : reference sublanding

 ### Outside the Services section

Still needs full review.

 * Entities that reuse the page entity fields to reference sublanding and landing section pages: `document_landing_page` `guide_overview` `html_page`
 * Entities referenced by services landingpage https://github.com/localgovdrupal/localgov_services/issues/6#issuecomment-630015242

## To Do / Done

Collecting summary from comments

 - [x] Move code from localgov_services_page
 - [x] Review `hook_form_alter` is it attaching validation to all forms
 - [x] Review valid sublanding page code, does it actually handle empty service

Devise opt-in system for external modules. Suggestion https://github.com/localgovdrupal/localgov_services/issues/6#issuecomment-630018910

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Sunday May 17, 2020 at 09:22 GMT_

----

As part of #2 moving the code related to navigation, and the specific reused navigation fields to a new module `localgov_services_navigation` with the hope that it will make it easier to refactor the navigation (and handle its reuse and dependencies outside the services section).

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 08:03 GMT_

----

Removing from `field.field.node.localgov_services_landing.field_destinations.yml` hard coded dependency on:-
        
`- node.type.basic_page`         
`- node.type.campaign_overview`                               
`- node.type.guide_overview`                     
`- node.type.step_by_step_homepage`

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Monday May 18, 2020 at 08:10 GMT_

----

Suggestion for opt-in configuration listing content types outside services that link or could be linked to. 

Use this to update config of dependencies of landing page entity reference. Alternative here is to replace the handler with one that calculates the bundle dependencies? List can also inform the https://github.com/localgovdrupal/localgov_services/blob/34e4b448d9796c5a69ce25df638a451e43c99cfb/modules/localgov_services_navigation/localgov_services_navigation.module#L48 list or even attach the fields.

**Comment by ekes** [comment]
So the `form_alter` is working on every form, but does then check for the field. So it's non-urgent.

Thinking through options maybe a better set up would be:
 * Single entity reference field with two values
 * Make a widget that restricts the values for the first field to services and then the second to the appropriate subservices. I'm assuming this is fiddly, but so is the present ajax for doing the same with two field (only difference is the latter is written already).
 * Make 'opting' in for a content type be using the widget. Store this for the list mentioned https://github.com/localgovdrupal/localgov_services/blob/943cc3d525b1378cbbe268a0db9b9ed5498c415e/modules/localgov_services_navigation/localgov_services_navigation.module#L47

**Comment by finnlewis** [comment]
That reminds me of an old post from Lullabot on extending entity reference fields: https://www.lullabot.com/articles/extending-a-field-type-in-drupal-8

**Comment by ekes** [comment]
> That reminds me of an old post from Lullabot on extending entity reference fields: https://www.lullabot.com/articles/extending-a-field-type-in-drupal-8

I had thought about combining the two entity reference fields. We ended up doing something like that on EC with references to both a term and a nodes. It's a bit more involved than just extending the entity reference with a simple field.

But also it occurred to me that this really is just one entity reference field. Really it could just store the _direct_ parent and the parent of that is calculated. But for easier form field js ux re-use, and for dx by having it available in storage, having both parents is good. I can't envisage any usage that just storing direct parent in delta 1 and top level parent in delta 0 isn't good enough. (or maybe the deltas the other way round - but anyway).

So this would be a core entity reference field allowing two values, but with a widget with alterations for the valid options callback and the validation. The code in localgov_services_navigation.module already does this for two fields, which might be simpler, than trying to combine them. But feels much cleaner to have one field that developers can attach to modules outside services to opt into referencing into services (and becoming something linked to from services).

**Comment by ekes** [comment]
#27 fixes the fundamental issue. Other links into pages working with follow-up issue to make the Administration Experience better: #44
