### ISSUE TITLE
Campaigns - banner colors discussion

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_services#62]
It's a worry that gradient and accent colors can be set separately:

- looks bad visually
- accessibility issues

My pref is that users can pick pairs of colors, and this would be reflected in the base theme, and there's an ability for these to carry through to any installed theme

**Comment by andybroomfield** [comment]
This belongs in localgov_campaigns / localgov_subsites. But I don't think its even an issue as they don't use this anymore.
