### ISSUE TITLE
UX tweaks to parent/ child relationship

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_services#63]
To discuss at the end of tomorrow's stand up 

Setting parent/ child relationships in the Services stack of pages is tripping up some users, and I want to make some minor changes before we test them again

We're planning to give them a revised version of the RBKC blog post to read

I would also like us to consider the following UX changes:

### On service pages 

eg https://localgovdrupal.agile.coop/node/42/edit

- Move the "Services:Parent" field to the top of the Content tab

- Label is as "Parent"

- Add the following helper text: "This sets the breadcrumb and the url alias for the page"

- Ensure it's not mandatory (right now it's starred)

### On service landing and sub-landing pages 

eg https://localgovdrupal.agile.coop/node/6/edit

- Leave the blue panel at the top of the page

- Give it a title "Pages linking here"

- Add helper text: "Drag and drop these to child pages below" or "Drag and drop these to child pages or task buttons below"

- Make the page panels smaller. There could be 20 pages linking here

**Comment by willguv** [comment]
We're pencilling in a session with Bracknell on 23/24 July so I'd like to make some progress on this by then

**Comment by finnlewis** [comment]
"Ensure it's not mandatory (right now it's starred)"
@ekes @stephen-cox  @Adnan-cds  any reason that we need to keep the services parent required?
