### ISSUE TITLE
Service status page is broken in demo site

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_services#66]
The tabbed content functionality of the Service status page isn't working in https://localgovdrupal.agile.coop/service-status or in local development sites.

This is caused by a CSS style rule for the **.tab-pane** selector.  This is coming from the localgov_theme Drupal theme and says
```
.tab-pane {
    display: block !important;
    opacity: 1;
}
```
If I turn off this rule, the expected behaviour is restored.

FAO @cjstevens78

**Comment by cjstevens78** [comment]
@Adnan-cds I have added a fix for this here https://github.com/localgovdrupal/localgov_theme/pull/49 for you to review

**Comment by Adnan-cds** [comment]
Thanks Chris, I will try the fix :)

FAO @cjstevens78

**Comment by stephen-cox** [comment]
Looks fixed. Closing
