### ISSUE TITLE
Agree default names for statuses in Service Status

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_services#68]
Limited
Revised
Normal 

isn't massively clear

Let's agree new out of the box names

**Comment by willguv** [comment]
@andybroomfield suggests have this in the back end

1- normal
2- minor disruption
3 - major disruption

Councils can easily give plain text values to each

Needs discovery about how best to provide this functionality

**Comment by andybroomfield** [comment]
Closing this for now, can be reopened if the conversation needs to be.
