### ISSUE TITLE
Add "task buttons" to Service sub landing page

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_services#70]
eg on https://new.croydon.gov.uk/planning-and-regeneration/building-control

**Comment by andybroomfield** [comment]
@willguv Has this been addressed? I don't see anything on the localgov version of Croydon.

**Comment by willguv** [comment]
@andybroomfield no, not addressed yet. On @tom-steel’s wish list too. Let’s estimate and try to schedule this work

**Comment by willguv** [comment]
Replaced by https://github.com/localgovdrupal/localgov_services/issues/151
