### ISSUE TITLE
Fields need to be renamed to start with localgov_ prefix

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_services#75]
When trying to install this module on existing BHCC site, error encountered as the fields cannot be installed as they already exists.
>`Error Unable to install LocalGov Services: Navigation, field.storage.node.field_common_tasks already exists in active configuration.`
>`Unable to install LocalGov Services: Page, field.storage.node.field_download_links, field.storage.node.field_hide_related_topics, field.storage.node.field_override_related_links, field.storage.node.field_related_links already exist in active configuration.`

Renaming the config folder to optional bypasses this issue, but the fields will be the existing BHCC fields so will not be the upgraded versions if any changes to them have been done.

If upgrading an existing field is supported, these fields will need to be renamed.

**Comment by andybroomfield** [comment]
Additional, the sub landing and landing also has errors
Sub landing page:
> `Unable to install LocalGov Services: Sub Landing page, core.entity_form_display.paragraph.topic_list_builder.default, core.entity_view_display.paragraph.topic_list_builder.default, field.storage.node.field_topics, paragraphs.paragraphs_type.topic_list_builder already exist in active configuration.` 
Landing page:
> `Unable to install LocalGov Services: Landing page, field.storage.node.field_address, field.storage.node.field_address_first_line, field.storage.node.field_contact_us_online, field.storage.node.field_destinations, field.storage.node.field_hearing_difficulties_phone, field.storage.node.field_link_to_map, field.storage.node.field_opening_hours, field.storage.node.field_other_team_contacts, field.storage.node.field_popular_topics, views.view.services already exist in active configuration.`

**Comment by finnlewis** [comment]
@stephen-cox noted that our thinking has evolved since the start of the project , we do want maintain consistent naming conventions with the localgov_ prefix wherever possible for fields

https://github.com/localgovdrupal/localgov/wiki/Naming-conventions

We might need to update that wiki page to follow.

**Comment by andybroomfield** [comment]
See comment on https://github.com/localgovdrupal/localgov_core/pull/37
> https://www.drupal.org/project/config_sync and migration may be a better method for handling this.

**Comment by andybroomfield** [comment]
This is done!
