### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_services#8]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ekes](https://github.com/ekes)**
_Sunday May 17, 2020 at 12:00 GMT_
_Originally opened as https://github.com/localgovdrupal/localgov_services_private/issues/8_

----

Holding issue for when the review is ready.

 - [x] Private Public topics on Services Page
 - [x] Paragraph type list on Services SubLanding
 - [x] Popular topics on Landing Page
 - [x] Topics on Landing Page

**Comment by ekes** [comment]
<a href="https://github.com/ekes"><img src="https://avatars3.githubusercontent.com/u/237186?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ekes](https://github.com/ekes)**
_Tuesday May 19, 2020 at 13:03 GMT_

----

Working to the broad guidelines suggested by @willcallaghan _for now_. This is being researched :: WIP.

Suggestion is: topics associated with content lower in the hierarchy (ie pages). So:-
 * Landing pages: no topics associated to the page itself; but the 'popular topics' manual link to topics remains as a separate field.
 * SubLanding pages: topic grouping of pages/links would remain but be enhanced. Again SubLanding aren't associated with a topic themselves, but 
 * Pages: have topics associated with them. How they use these to pull (suggested) related pages remains to be fixed. Hidden topics remain with question mark by them.

**Comment by ekes** [comment]
Topics should be on the landing page correctly.

To do : review , add a test.

**Comment by ekes** [comment]
Popular topics is there to link _to_ topics.
Topics isn't there to put a landing page _in_ a topic. Based on will's guidelines above.

**Comment by stephen-cox** [comment]
Closes at sprint 1 review.
