### ISSUE TITLE
Generate the services menu

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_services#82]
Build out a menu that is a link to all service landing pages.
To aid building out the services mega menu in the theme, and to provide other themes with a menu for all services. 
This could either be a view, or a menu where every service landing page gets an entry.

**Comment by andybroomfield** [comment]
Should this be a config change so it defaults to adding every service landing page to the services menu, which means content designers could selectively exclude them. Or it could just be a menu that builds out all the service landing page.
Would need an update hook to install the menu and populate it with previously added service landing pages.

**Comment by andybroomfield** [comment]
We could use [Menu Force](https://www.drupal.org/project/menu_force) for this, but this forces a menu link to be added which I'm not so sure is what we want.

**Comment by ekes** [comment]
While I was working on https://github.com/ekes/localgov_campaigns/tree/feature/hierarchy I looked at how entity_hierarchy builds its microsite menus. [As it happens I opt-ed for building menus that theme the same but don't actually make menu items https://github.com/ekes/localgov_campaigns/commit/9a3e48578cd648df9a8cbb4e1c55fd90567b421a ] but anyway it does in code the control of menu items which might be of interest.

More generally Entity Hierarchy itself is overkill for the enforced maximum two level structure of services; but for Campaigns as seperate sections (or Engagement content or whatever) with an arbitrary menu structure and depth it made sense. Once there though it might make sense for other sections. It does make it _very_ easy to pull up the full structure of all the campaigns (and would do the same elsewhere).

But back to controlling menu items. If you look at the code of entity_hierarchy_microsite it actually adds itself as a menu https://git.drupalcode.org/project/entity_hierarchy/-/blob/8.x-2.x/modules/entity_hierarchy_microsite/entity_hierarchy_microsite.links.menu.yml and adds menu items https://git.drupalcode.org/project/entity_hierarchy/-/tree/8.x-2.x/modules/entity_hierarchy_microsite/src/Plugin/Menu https://git.drupalcode.org/project/entity_hierarchy/-/tree/8.x-2.x/modules/entity_hierarchy_microsite/src/Plugin/Deriver ] Maybe of interest.

**Comment by andybroomfield** [comment]
Closing as no longer required.
