### ISSUE TITLE
Body field issues

### ISSUE THREAD

**Issue by gosia-mlynarczyk** [localgovdrupal/localgov_services#85]
Hi,

Our client (from Bracknell Forest Council) had a look at the demo site we set up for them to have look around and play with Service pages, and they asked us why the Body field is not displayed anywhere.

I checked and discovered that the Body (with summary) field on the Service landing page content type is mandatory, and so is the summary. The display mode for teasers has that field set to '_Summary or trimmed: If the summary is not set, use the trimmed Body field_'). But since the Summary is mandatory the contents of the Body field will never be displayed in teasers. 

I can edit that field's settings and change the summary to 'optional', fixing the teasers issue, but the Body field is still not displayed on Service landing pages ('Default' view mode). If the summary is provided, it's displayed below the title (in page header block), but if the summary field is left empty, and there's content in the Body field, it's not displayed anywhere on the page. 

Is this intentional?

**Comment by stephen-cox** [comment]
Hi Gosia,

Just noticed this.

I think this is a hangover from the Croydon port. They don't use the main body field, only the summary and it probably should have been set as just a test field that is displayed under the title and in teasers. If Bracknell want the body then it should be easy enough to change the node display to have this shown. If they don't then perhaps we should change the field to just a summary to avoid confusion.

Is this still causing issues or have you found a solution?

Thanks,

Stephen

**Comment by andybroomfield** [comment]
@stephen-cox I belive guides / Guide overview pages have a seperate field for this. Its been a bit of a bugbear that there are mandatory but non displayed body fields so I would like to see these replacded. It would hovewever be good to get consistency as it will mean some content types use the body summary for the 'lede' and teasers on service landing lists, whereas others will have a specilist field. Perhaps they should all be replaced? In the mean time I would suggest replacing this on Service landing with a dedicated summary field.

**Comment by markconroy** [comment]
At a very minimum we should set the body field to optional. Then figure out a more consistent approach.

**Comment by ekes** [comment]
Does anyone in the thread above want to confirm the #101 approach? If so I'll merge it before tagging #103

**Comment by stephen-cox** [comment]
Making the body optional for now make sense :+1:
