### ISSUE TITLE
Allow display mode to be configured in custom LinkNodeReference field formatter

### ISSUE THREAD

**Issue by tanc** [localgovdrupal/localgov_services#89]
At the moment the field formatter for the links field in services is hard coded to use the `teaser` display mode. It would make sense to a front-end developer to be able to configure this to point to a different display mode so that teaser can be decoupled from this particular field.

A use case could be that the teaser is used across the site to display a title, a short summary and a link to the full node, as is common. But when displaying a list of services a tile grid needs to be shown which consists only of a title. For this to work the two display modes would need to be different.

Currently on Lambeth there is the tile view mode which is used in a different component but there is also this teaser view mode which is used for this component, making for duplication and confusion.

**Comment by andybroomfield** [comment]
This might be one for @markconroy advice. I would suggest a new display mode for this so any content could be opted into landing / sub landing pages. BHCC typically link to pages outside the service stack that can have weird teasers, so a common format for displaying in service landing pages would fit better and could allow a unified template.

**Comment by markconroy** [comment]
I support the idea of being able to choose the view mode.

@andybroomfield All content in a view mode "teaser" should look similar. We really should not be using "Teaser" as "the content display when it's in a list". We should have a default for what a teaser looks like, a card looks like, a search result looks like, a tile looks like, etc. Then we would be able to reference any content across the website and be confident we wouldn't have some of it looking weird.

On annertech.com here's an example of different content types using the same view mode: https://www.annertech.com/themes/custom/weatherlab/pattern-lab/public/?p=viewall-content-display-card

That allows/encourages much more consistence across the site. The only difference between content types with the same view mode is some individual fields (events might have a date that not available on other content types, for example).

**Comment by andrew-wallis** [comment]
Hi @markconroy @tanc - we've also run into this issue and have a fix for our local site. It adds a configurable field to the Link field formatter that pulls through all available view modes for nodes. For us, it will be either card or teaser but it is dynamically generated from the view mode list. I'll look at contributing this back to LocalGov core.

**Comment by andrew-wallis** [comment]
This has now been fixed in the latest version of localgov_services
