### ISSUE TITLE
Linking to non-D8 pages from D8 landing pages

### ISSUE THREAD

**Issue by OliverHannan** [localgovdrupal/localgov_services#93]
Adding either external or D7 links to D8 landing pages, there is no option to add summary text, summary text is not pulled through from D7 pages. Just left with the title - see these 2 pages.

![image](https://user-images.githubusercontent.com/47107641/110963151-a50ee480-8349-11eb-85cf-9546a1f7471d.png)

https://lbc-app-w-corpwebsite-p.azurewebsites.net/business-licences-and-tenders/running-business/business-support-and-advice

![image](https://user-images.githubusercontent.com/47107641/110963203-b3f59700-8349-11eb-8b93-d4ac6cbee4b5.png)

https://lbc-app-w-corpwebsite-p.azurewebsites.net/business-licences-and-tenders/running-business

Is there any way to rectify or bypass this?

**Comment by andybroomfield** [comment]
BHCC Would also be interested in this (Our solution is to set up redirect pages that can be included with a teaser, but then link off).

What would be the best way forward? A field formatter that if its an external link could add a custom summary?

**Comment by danchamp** [comment]
> BHCC Would also be interested in this (Our solution is to set up redirect pages that can be included with a teaser, but then link off).

Cumbria have also just bumped up against this issue. I came up with the same workaround @andybroomfield but it's a bit ugly!

**Comment by andybroomfield** [comment]
I think there is scope here to change the link format fir sub hubs as they are paragraphs (or are they link fields) and have the option to craft a custom snippet here if something can't be picked up.

Else the alternative would be to have a crawler go out and fetch the external page and use the meta description tag.

**Comment by andybroomfield** [comment]
A quick bump on this.
I notice in sub landing module (and in legacy BHCC code) there is a dummy-teaser.html.twig template that gets used for external links. This has space for the link title and url. It could be expanded to also include some teaser text? and the field widget could add extra support for a manually crafted teaser.
External links seem to crop up a lot, and as its a link field not an entity reference, they should be supported.
This could also extend to support links to pages that do not have teasers such as views so there is fallback to implement some summary text.

**Comment by willguv** [comment]
Replaced by https://github.com/localgovdrupal/localgov_services/issues/152 with an updated description, linked back here for conversation
